# Generated by Django 5.1.5 on 2025-01-26 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='titleOfTask')),
                ('text', models.CharField(max_length=400, null=True, verbose_name="task's_text")),
                ('is_updated', models.BooleanField(default=False, verbose_name='is_updated?')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is_completed?')),
                ('created_datetime', models.DateTimeField(default=datetime.datetime(2025, 1, 26, 20, 26, 46, 997517, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-id'],
            },
        ),
    ]
