# Generated by Django 5.1.5 on 2025-01-26 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 20, 26, 54, 558345, tzinfo=datetime.timezone.utc)),
        ),
    ]
