# Generated by Django 5.1.5 on 2025-01-27 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 5, 42, 23, 282008, tzinfo=datetime.timezone.utc)),
        ),
    ]
