# Generated by Django 5.1.5 on 2025-01-27 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_task_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 6, 39, 17, 927847, tzinfo=datetime.timezone.utc)),
        ),
    ]
