# Generated by Django 5.1.5 on 2025-01-27 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_task_created_datetime_alter_task_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 6, 43, 3, 98505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted?'),
        ),
    ]
